[package]
name = "vprytz-task-15"
version = "0.1.0"
edition = "2021"
authors = ["Vilhelm Prytz <vilhelm@prytznet.se>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
